-- Add missing columns to Location table
ALTER TABLE "Location"
  ADD COLUMN IF NOT EXISTS "menuCategories" JSONB,
  ADD COLUMN IF NOT EXISTS "posterSubdomain" TEXT,
  ADD COLUMN IF NOT EXISTS "posterAccount" TEXT,
  ADD COLUMN IF NOT EXISTS "posterToken" TEXT,
  ADD COLUMN IF NOT EXISTS "googlePlaceId" TEXT,
  ADD COLUMN IF NOT EXISTS "googleMapsUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "busyMode" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "busyModeUntil" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "maxQueueSize" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "hasPrinter" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "printerIp" TEXT;

-- Add missing columns to User table
ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "birthDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastBirthdayBonus" INTEGER,
  ADD COLUMN IF NOT EXISTS "referredById" INTEGER,
  ADD COLUMN IF NOT EXISTS "referralBonusPaid" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "preferredLocationId" INTEGER,
  ADD COLUMN IF NOT EXISTS "phone" TEXT,
  ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'uk',
  ADD COLUMN IF NOT EXISTS "noShowCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cashPaymentBlocked" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "notifSpin" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "notifWinback" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "notifMorning" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "notifPromo" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "onboardingDone" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "radioGenre" TEXT,
  ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

-- Add missing columns to Product table
ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "posterProductId" TEXT,
  ADD COLUMN IF NOT EXISTS "ingredients" TEXT,
  ADD COLUMN IF NOT EXISTS "telegramFileId" TEXT,
  ADD COLUMN IF NOT EXISTS "imageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "calories" INTEGER,
  ADD COLUMN IF NOT EXISTS "volume" TEXT,
  ADD COLUMN IF NOT EXISTS "allergens" TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "tags" TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "modifiers" JSONB,
  ADD COLUMN IF NOT EXISTS "ordersCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "categoryOrder" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- Add missing columns to Order table
ALTER TABLE "Order"
  ADD COLUMN IF NOT EXISTS "shiftId" INTEGER,
  ADD COLUMN IF NOT EXISTS "posterOrderId" TEXT,
  ADD COLUMN IF NOT EXISTS "discount" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "promoCode" TEXT,
  ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT NOT NULL DEFAULT 'cash',
  ADD COLUMN IF NOT EXISTS "paymentId" TEXT,
  ADD COLUMN IF NOT EXISTS "pointsUsed" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "pickupTime" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "estimatedReady" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "qrCode" TEXT,
  ADD COLUMN IF NOT EXISTS "comment" TEXT,
  ADD COLUMN IF NOT EXISTS "isRepeat" BOOLEAN NOT NULL DEFAULT false;

-- Add missing columns to OrderItem table
ALTER TABLE "OrderItem"
  ADD COLUMN IF NOT EXISTS "bundleId" INTEGER,
  ADD COLUMN IF NOT EXISTS "modifiers" JSONB;

-- Add missing columns to Shift table
ALTER TABLE "Shift"
  ADD COLUMN IF NOT EXISTS "ordersCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "avgRating" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "totalTips" DECIMAL(10,2) NOT NULL DEFAULT 0;

-- Add missing columns to Bundle table
ALTER TABLE "Bundle"
  ADD COLUMN IF NOT EXISTS "telegramFileId" TEXT,
  ADD COLUMN IF NOT EXISTS "imageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- Add missing columns to Review table
ALTER TABLE "Review"
  ADD COLUMN IF NOT EXISTS "shiftId" INTEGER,
  ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN NOT NULL DEFAULT false;
